### ISSUE TITLE
Found unique constraint from Database, but still the diff command generates a <addUniqueConstraint .

### ISSUE THREAD

**Issue by Nagendra080389** [liquibase/liquibase-hibernate#112]
While running diff command, it finds the hbm and connects to database and find the respective unique key constraints in the schema, but while generating auto log it still generates <addUniqueKeyConstraint of the same ID attribute but with a different name. 
 
Shouldn't it generate only those attributes or unique key constraint or foreignkeyConstraint which are not found in database schema.
Is this a bug?

**Comment by nvoxland** [comment]
Fixed with liquibase-hibernate 3.6

**Comment by dpansica** [comment]
I'm still having this problem using liquibase-hibernate 3.6.
